// Real Chromium integration via Playwright. Run: npm run test:browser
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..');
// Repeating 392Hz signal through Chromium's fake microphone device, no external audio.
const wave=path.join(root,'tests','test-voice.wav'),rate=48000,length=rate*3,buffer=Buffer.alloc(44+length*2);buffer.write('RIFF');buffer.writeUInt32LE(buffer.length-8,4);buffer.write('WAVEfmt ',8);buffer.writeUInt32LE(16,16);buffer.writeUInt16LE(1,20);buffer.writeUInt16LE(1,22);buffer.writeUInt32LE(rate,24);buffer.writeUInt32LE(rate*2,28);buffer.writeUInt16LE(2,32);buffer.writeUInt16LE(16,34);buffer.write('data',36);buffer.writeUInt32LE(length*2,40);for(let i=0;i<length;i++)buffer.writeInt16LE(Math.round(6000*(Math.sin(2*Math.PI*392*i/rate)+.3*Math.sin(4*Math.PI*392*i/rate))),44+i*2);fs.writeFileSync(wave,buffer);
const server=spawn('python3',['-m','http.server','8766','--bind','127.0.0.1'],{cwd:root,stdio:'ignore'});
(async()=>{let browser;try{
for(let i=0;i<40;i++){try{if((await fetch('http://127.0.0.1:8766')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
browser=await chromium.launch({args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--use-file-for-fake-audio-capture='+wave]});
const context=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true,permissions:['microphone']});const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
await page.goto('http://127.0.0.1:8766/');await page.waitForFunction(()=>document.querySelector('#start')?.onclick);
assert.equal(await page.locator('[data-window="30"]').getAttribute('aria-pressed'),'true');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.getByRole('button',{name:'● 測定を始める',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#stableHigh').textContent.includes('mid2G'),{},{timeout:15000});await page.screenshot({path:root+'/tests/mobile-live.png',fullPage:true});
await page.getByRole('button',{name:'■ 終了',exact:true}).click();await page.locator('#comment').fill('Chromium microphone and IndexedDB test');await page.getByRole('button',{name:'練習結果を保存',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#save').textContent==='保存済み');
await page.reload();await page.getByRole('button',{name:'練習履歴',exact:true}).click();await page.getByRole('button',{name:'軌跡を見る',exact:true}).click();assert.ok((await page.locator('#stableHigh').textContent()).includes('mid2G'));
await page.getByRole('button',{name:'全体',exact:true}).click();assert.equal(await page.locator('#graphState').textContent(),'セッション全体');
await page.getByRole('button',{name:'発声練習',exact:true}).click();await page.locator('#endNote').selectOption('48');await page.getByText('テンポ・音量・プリセット',{exact:true}).click();await page.locator('#tempo').fill('160');await page.getByRole('button',{name:'▶ お手本から始める',exact:true}).click();await page.waitForTimeout(1500);assert.equal(await page.locator('#currentNote').textContent(),'—');await page.waitForFunction(()=>document.querySelector('#phaseLabel').textContent.includes('あなたの番 · 表示'),{},{timeout:10000});await page.waitForFunction(()=>document.querySelector('#currentNote').textContent.includes('mid2G'),{},{timeout:4000});await page.getByRole('button',{name:'一時停止',exact:true}).click();assert.equal(await page.locator('#currentNote').textContent(),'—');await page.getByRole('button',{name:'再開',exact:true}).click();await page.getByRole('button',{name:'■ 終了',exact:true}).click();
await page.getByRole('button',{name:'設定',exact:true}).click();await page.locator('#noteFormat').selectOption('international');await page.getByRole('button',{name:'設定を閉じる',exact:true}).click();
// Wait for cache install then check an actual network-off navigation and module/worker availability.
await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>document.querySelector('#start')?.onclick);assert.equal(await page.locator('#modeTitle').textContent(),'声の動きを、見てみよう。');await page.getByRole('button',{name:'練習履歴',exact:true}).click();await page.getByRole('button',{name:'軌跡を見る',exact:true}).click();assert.equal(await page.locator('#stableHigh').textContent(),'G4');
await page.getByRole('button',{name:'● 測定を始める',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#currentNote').textContent==='G4',{},{timeout:10000});await page.getByRole('button',{name:'■ 終了',exact:true}).click();
assert.deepEqual(errors,[]);console.log('PASS: real Chromium mobile viewport; fake-mic input; YIN worker; stable range; call/response; pause/stop; IndexedDB survives reload; format persists; actual offline reload and worker; no page errors.');
}finally{await browser?.close();server.kill();fs.rmSync(wave,{force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
