import test from 'node:test';
import assert from 'node:assert/strict';
import {detectPitch,midiToHz,hzToMidi,noteName,PitchTracker,SessionStats,toneStats,SCALE} from '../pitch.js';
function signal(hz,{rate=48000,amplitude=.2,harmonics=[1],noise=0,vibrato=0}={}){let phase=0,seed=123;return Float32Array.from({length:8192},(_,i)=>{seed=(seed*1664525+1013904223)>>>0;phase+=2*Math.PI*hz*2**(vibrato*Math.sin(2*Math.PI*5*i/rate)/1200)/rate;return amplitude*harmonics.reduce((s,a,h)=>s+a*Math.sin(phase*(h+1)),0)+(seed/4294967296-.5)*noise;});}
for(const rate of [44100,48000])for(const midi of [33,36,43,48,55,60,67,72,79,84])test(`YIN ${noteName(midi)} / ${rate}Hz`,()=>{const result=detectPitch(signal(midiToHz(midi),{rate}),rate);assert.ok(result.hz);assert.ok(Math.abs(1200*Math.log2(result.hz/midiToHz(midi)))<8);});
for(const midi of [40,48,60,67,76])test(`dominant second harmonic and breath noise ${midi}`,()=>{const hz=midiToHz(midi),result=detectPitch(signal(hz,{harmonics:[.18,1,.4,.15],noise:.025}),48000);assert.ok(result.hz);assert.ok(Math.abs(1200*Math.log2(result.hz/hz))<10);});
test('silence, weak voice and seeded broadband noise are rejected',()=>{assert.equal(detectPitch(new Float32Array(8192),48000).hz,null);assert.equal(detectPitch(signal(220,{amplitude:.001}),48000).hz,null);assert.equal(detectPitch(signal(0,{amplitude:0,noise:.3}),48000).hz,null);});
test('modest vocal vibrato remains detected',()=>{const d=detectPitch(signal(220,{harmonics:[1,.4,.2],vibrato:20}),48000);assert.ok(d.hz);assert.ok(Math.abs(1200*Math.log2(d.hz/220))<25);});
test('Japanese and international mapping',()=>{assert.equal(noteName(48),'mid1C (C3)');assert.equal(noteName(55),'mid1G (G3)');assert.equal(noteName(60),'mid2C (C4)');assert.equal(noteName(67),'mid2G (G4)');assert.equal(noteName(72),'hiC (C5)');assert.equal(noteName(null),'—');assert.equal(noteName(67,'international'),'G4');assert.equal(noteName(67,'japanese'),'mid2G');assert.equal(hzToMidi(440),69);});
test('single-frame spikes excluded; intentional octave accepted after confirmation',()=>{const tracker=new PitchTracker(),d=m=>({hz:midiToHz(m),confidence:.98});assert.equal(tracker.accept(d(48),0),null);assert.equal(tracker.accept(d(48),.05),48);assert.equal(tracker.accept(d(60),.10),null);assert.equal(tracker.accept(d(48),.15),48);assert.equal(tracker.accept(d(60),.20),null);assert.equal(tracker.accept(d(60),.25),null);assert.equal(tracker.accept(d(60),.30),60);});
test('stable limits require duration; transient high remains instantaneous only',()=>{const s=new SessionStats();for(let i=0;i<12;i++)s.add(i*.05,48+Math.sin(i)*.04,.98);s.add(.6,null);s.add(.65,72,.98);assert.equal(s.summary().stableLow,48);assert.equal(s.summary().stableHigh,48);assert.equal(s.summary().high,72);});
test('breaths split stable runs; unstable ramps rejected',()=>{const s=new SessionStats();for(let i=0;i<20;i++){s.add(i*.1,60,.98);s.add(i*.1+.05,null);}assert.equal(s.summary().stableLow,null);const ramp=new SessionStats();for(let i=0;i<20;i++)ramp.add(i*.05,50+i*.15,.98);assert.equal(ramp.summary().stableLow,null);});
test('stability matches its documented formula and target error',()=>{const result=toneStats([{m:66.92},{m:66.92},{m:66.92},{m:66.92}],67);assert.ok(Math.abs(result.error+8)<1e-9);assert.equal(result.score,100);assert.equal(toneStats([{m:null}]),null);});
test('five-tone major scale and semitone transposition',()=>{assert.deepEqual(SCALE.map(n=>n+48),[48,50,52,53,55,53,52,50,48]);assert.deepEqual(SCALE.map(n=>n+47),[47,49,51,52,54,52,51,49,47]);});
